version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - yoga-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yoga_db
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d yoga_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c log_statement=all

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db/yoga_db
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://nginx
    networks:
      - yoga-network
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE=http://localhost/api
    networks:
      - yoga-network

volumes:
  postgres_data:

networks:
  yoga-network:
    driver: bridge 